// Code generated by "enumer -type=errorKind -output errors_gen.go"; DO NOT EDIT.

package streams

import (
	"fmt"
	"strings"
)

const _errorKindName = "TypeErrorRangeErrorRuntimeErrorAssertionError"

var _errorKindIndex = [...]uint8{0, 9, 19, 31, 45}

const _errorKindLowerName = "typeerrorrangeerrorruntimeerrorassertionerror"

func (i errorKind) String() string {
	i -= 1
	if i >= errorKind(len(_errorKindIndex)-1) {
		return fmt.Sprintf("errorKind(%d)", i+1)
	}
	return _errorKindName[_errorKindIndex[i]:_errorKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _errorKindNoOp() {
	var x [1]struct{}
	_ = x[TypeError-(1)]
	_ = x[RangeError-(2)]
	_ = x[RuntimeError-(3)]
	_ = x[AssertionError-(4)]
}

var _errorKindValues = []errorKind{TypeError, RangeError, RuntimeError, AssertionError}

var _errorKindNameToValueMap = map[string]errorKind{
	_errorKindName[0:9]:        TypeError,
	_errorKindLowerName[0:9]:   TypeError,
	_errorKindName[9:19]:       RangeError,
	_errorKindLowerName[9:19]:  RangeError,
	_errorKindName[19:31]:      RuntimeError,
	_errorKindLowerName[19:31]: RuntimeError,
	_errorKindName[31:45]:      AssertionError,
	_errorKindLowerName[31:45]: AssertionError,
}

var _errorKindNames = []string{
	_errorKindName[0:9],
	_errorKindName[9:19],
	_errorKindName[19:31],
	_errorKindName[31:45],
}

// errorKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func errorKindString(s string) (errorKind, error) {
	if val, ok := _errorKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _errorKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to errorKind values", s)
}

// errorKindValues returns all values of the enum
func errorKindValues() []errorKind {
	return _errorKindValues
}

// errorKindStrings returns a slice of all String values of the enum
func errorKindStrings() []string {
	strs := make([]string, len(_errorKindNames))
	copy(strs, _errorKindNames)
	return strs
}

// IsAerrorKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i errorKind) IsAerrorKind() bool {
	for _, v := range _errorKindValues {
		if i == v {
			return true
		}
	}
	return false
}
