#!/usr/bin/env sh

cd .. && \
  xk6 build --with github.com/grafana/xk6-output-prometheus-remote=. && \
  K6_PROMETHEUS_REMOTE_URL=http://localhost:9090/api/v1/write ./k6 run example/test.js -o output-prometheus-remote