run:
  deadline: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # We want to try and improve the comments in the k6 codebase, so individual
  # non-golint items from the default exclusion list will gradually be addded
  # to the exclude-rules below
  exclude-use-default: false

  exclude-rules:
   # Exclude duplicate code and function length and complexity checking in test
   # files (due to common repeats and long functions in test code)
   - path: _(test|gen)\.go
     linters:
       - gocyclo
       - dupl
       - gocognit
       - funlen
       - lll
   - linters:
     - paralleltest # false positive: https://github.com/kunwardeep/paralleltest/issues/8.
     text: "does not use range value in test Run"

  exclude:
   #TODO: remove this exclusion after https://github.com/golang/lint/issues/381
   # is fixed by https://github.com/golang/lint/pull/380 or something else
   - "should have a package comment, unless it's in another file for this package"

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 10
    min-occurrences: 4
  funlen:
    lines: 80
    statements: 60
  goheader:
    template-path: ".license-template"
    values:
      const:
        year: 2021
      regexp:
        year-range: (\d\d\d\d|{{year}})

linters:
  enable-all: true
  disable:
  - nlreturn
  - gci
  - gochecknoinits
  - godot
  - godox
  - gomodguard
  - testpackage
  - wsl
  - gomnd
  - goerr113 # most of the errors here are meant for humans
  - goheader
  - exhaustivestruct
  - thelper
  - maligned # replaced by govet 'fieldalignment'
  - interfacer # deprecated
  - scopelint # deprecated, replaced by exportloopref
  - wrapcheck # a little bit too much for k6, maybe after https://github.com/tomarrell/wrapcheck/issues/2 is fixed
  fast: false
