# v1.55.2
# Please don't remove the first line. It uses in CI to determine the golangci version
run:
  deadline: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # We want to try and improve the comments in the k6 codebase, so individual
  # non-golint items from the default exclusion list will gradually be added
  # to the exclude-rules below
  exclude-use-default: false

  exclude-rules:
   # Exclude duplicate code and function length and complexity checking in test
   # files (due to common repeats and long functions in test code)
   - path: _(test|gen)\.go
     linters:
       - cyclop
       - dupl
       - gocognit
       - funlen
       - lll
   - linters:
     - staticcheck # Tracked in https://github.com/grafana/xk6-grpc/issues/14
     text: "The entire proto file grpc/reflection/v1alpha/reflection.proto is marked as deprecated."
   - linters:
     - forbidigo
     text: 'use of `os\.(SyscallError|Signal|Interrupt)` forbidden'

linters-settings:
  nolintlint:
    # Disable to ensure that nolint directives don't have a leading space. Default is true.
    allow-leading-space: false
  exhaustive:
    default-signifies-exhaustive: true
  govet:
    check-shadowing: true
  cyclop:
    max-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 10
    min-occurrences: 4
  funlen:
    lines: 80
    statements: 60
  forbidigo:
    forbid:
      - '^(fmt\\.Print(|f|ln)|print|println)$'
      # Forbid everything in os, except os.Signal and os.SyscalError
      - '^os\.(.*)$(# Using anything except Signal and SyscallError from the os package is forbidden )?'
      # Forbid everything in syscall except the uppercase constants
      - '^syscall\.[^A-Z_]+$(# Using anything except constants from the syscall package is forbidden )?'
      - '^logrus\.Logger$'

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  fast: false
