name: "Test common"
description: "Pre-test steps: Go install and optional Chromium install"

inputs:
  go_version:
    description: "Go version (eg 1.25.x) or gotip."
    required: false
    default: "1.25.x"
  platform:
    description: "matrix.platform value (used for windows/arm detection)."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Go
      if: ${{ inputs.go_version != 'gotip' }}
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version: ${{ inputs.go_version }}
        check-latest: true

    - name: Download and install Go tip
      if: ${{ inputs.go_version == 'gotip' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PLATFORM: ${{ inputs.platform }}
      run: |
        gh release download ${PLATFORM} --repo grafana/gotip --pattern 'go.zip'
        unzip go.zip -d $HOME/sdk

    - name: Install chromium
      # This is only needed on arm images, chromium comes preinstalled on amd64 runner images.
      if: ${{contains(inputs.platform, 'arm') }}
      shell: bash
      run: |
        sudo apt update && sudo apt install chromium-browser
        chromium --version || true