name: "Test common"
description: "Pre-test steps: Go install and optional Chromium install"

inputs:
  go_version:
    description: "Go version (eg 1.25.x) or gotip."
    required: false
    default: "1.25.x"
  platform:
    description: "matrix.platform value (used for windows/arm detection)."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Go
      if: ${{ inputs.go_version != 'gotip' }}
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
      with:
        go-version: ${{ inputs.go_version }}
        check-latest: true

    - name: Download and install Go tip
      if: ${{ inputs.go_version == 'gotip' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PLATFORM: ${{ inputs.platform }}
      run: |
        gh release download ${PLATFORM} --repo grafana/gotip --pattern 'go.zip'
        unzip go.zip -d $HOME/sdk

    - name: Install chromium
      # This is only needed on arm images, chromium comes preinstalled on amd64 runner images.
      if: ${{contains(inputs.platform, 'arm') }}
      shell: bash
      run: |
        set -euo pipefail

        if command -v chromium >/dev/null 2>&1; then
          chromium --version || true
          exit 0
        fi

        # Installing Chromium via snap avoids failing apt updates when runner images include
        # third-party apt repos that may be temporarily unavailable.
        if command -v snap >/dev/null 2>&1; then
          sudo snap install chromium || sudo snap refresh chromium
        else
          sudo apt-get update
          sudo apt-get install -y chromium-browser
        fi

        chromium --version
