/**
 * **TCP Protocol Extension for k6**
 *
 * This extension provides TCP socket functionality for k6 performance testing scripts,
 * offering Promise-based APIs for network communication.
 *
 * Supports event-driven programming with lifecycle events (connect, data, close, error, timeout),
 * TLS/SSL encryption, binary data handling, and comprehensive metrics collection.
 *
 * @module k6/x/tcp
 * @example
 * ```typescript
 * import { Socket } from 'k6/x/tcp';
 *
 * export default async function () {
 *   const socket = new Socket();
 *
 *   socket.on('data', (data) => {
 *     const response = String.fromCharCode.apply(null, new Uint8Array(data));
 *     console.log('Received:', response.substring(0, 100));
 *     socket.destroy();
 *   });
 *
 *   socket.on('close', () => {
 *     console.log('Connection closed');
 *   });
 *
 *   await socket.connect(80, 'example.com');
 *   await socket.write('GET / HTTP/1.1\r\nHost: example.com\r\n\r\n');
 * }
 * ```
 */
declare module "k6/x/tcp" {
  /**
   * Configuration options for creating a new TCP socket.
   *
   * @example
   * ```typescript
   * const socket = new Socket({
   *   tags: { endpoint: 'api', environment: 'prod' }
   * });
   * ```
   */
  export interface SocketOptions {
    /**
     * Optional key-value pairs for metrics collection and logging.
     * These tags will be attached to all metrics generated by this socket.
     */
    tags?: Record<string, string>;
  }

  /**
   * Represents the current state of a TCP socket connection.
   * 
   * Socket lifecycle transitions:
   * - `disconnected` → Initial state after construction
   * - `opening` → During connection establishment
   * - `open` → Successfully connected and ready for I/O
   * - `destroyed` → Terminal state, socket cannot be reused
   */
  export type SocketState =
    | 'opening'       // Socket is in the process of establishing a connection
    | 'open'          // Socket is connected and ready for bidirectional communication
    | 'destroyed'     // Socket has been destroyed and is unusable
    | 'disconnected'; // Socket is not connected to any remote endpoint

  /**
   * Events that can be emitted by a TCP socket during its lifecycle.
   * Use these with the `on()` method to handle socket events.
   */
  export type SocketEvent =
    | 'connect'    // Emitted when the socket successfully establishes a connection
    | 'data'       // Emitted when data is received from the remote endpoint
    | 'close'      // Emitted when the socket connection is fully closed
    | 'error'      // Emitted when a socket error occurs
    | 'timeout';   // Emitted when the socket times out due to inactivity

  /**
   * Configuration options for establishing a TCP socket connection.
   *
   * @example
   * ```typescript
   * // Basic connection
   * await socket.connect({
   *   port: 8080,
   *   host: 'api.example.com',
   *   tags: { service: 'api-server' }
   * });
   * 
   * // Secure TLS connection
   * await socket.connect({
   *   port: 443,
   *   host: 'secure.example.com',
   *   tls: true,
   *   tags: { protocol: 'tls' }
   * });
   * ```
   */
  export interface ConnectOptions {
    /** The destination port number or numeric string (1-65535) */
    port: number | string;
    /** The destination hostname or IP address. Defaults to 'localhost' */
    host?: string;
    /**
     * Enable TLS/SSL encryption for this connection.
     * 
     * When enabled, the socket will perform a TLS handshake after establishing
     * the TCP connection. TLS configuration (certificates, verification, cipher
     * suites, etc.) is controlled by k6's standard TLS settings.
     * 
     * Common use cases:
     * - Secure database connections (PostgreSQL, MySQL with TLS)
     * - HTTPS requests over raw TCP
     * - SMTPS, IMAPS mail protocols
     * - Custom secure protocols
     * 
     * @see https://grafana.com/docs/k6/latest/using-k6/protocols/ssl-tls/
     * @default false
     * @example
     * ```typescript
     * // Connect to HTTPS port with TLS
     * await socket.connect({
     *   port: 443,
     *   host: 'api.example.com',
     *   tls: true
     * });
     * ```
     */
    tls?: boolean;
    /**
     * Optional key-value pairs for metrics collection and logging.
     * These tags will be attached to connection-related metrics.
     *
     * This is provided for convenience since tags can also be specified
     * during socket creation via SocketOptions. Tags specified here will
     * override tags with the same name specified when creating the socket.
     */
    tags?: Record<string, string>;
  }

  /**
   * Configuration options for writing data to a TCP socket.
   *
   * @example
   * ```typescript
   * // Write base64-encoded data
   * await socket.write('SGVsbG8gV29ybGQ=', {
   *   encoding: 'base64',
   *   tags: { operation: 'send-auth-token' }
   * });
   * 
   * // Write hex-encoded binary data
   * await socket.write('48656c6c6f', {
   *   encoding: 'hex',
   *   tags: { data_type: 'binary' }
   * });
   * ```
   */
  export interface WriteOptions {
    /**
     * The encoding to use when data is a string.
     * 
     * Supported encodings:
     * - `'utf8'` / `'utf-8'` (default): UTF-8 text encoding
     * - `'ascii'`: Raw byte conversion for write operations
     * - `'base64'`: Base64-encoded data decoded to bytes before sending
     * - `'base64url'`: URL-safe Base64 decoded to bytes before sending
     * - `'hex'`: Hexadecimal string decoded to bytes before sending
     * 
     * Unsupported values are rejected.
     * When writing an ArrayBuffer, this option is ignored.
     */
    encoding?: string;
    /**
     * Optional key-value pairs for metrics collection and logging.
     * These tags will be attached to write-related metrics for this specific operation.
     *
     * Tags specified here will be merged with socket-level and connection-level tags.
     * Operation-level tags take highest priority for duplicate keys.
     */
    tags?: Record<string, string>;
  }

  /**
   * TCP Socket implementation for k6 performance testing.
   *
   * Provides a Node.js-compatible API for TCP socket operations, adapted for the k6 environment.
   * Supports Promise-based operations with comprehensive event handling.
   *
   * @example
   * ```typescript
   * import { Socket } from 'k6/x/tcp';
   *
   * const socket = new Socket();
   *
   * socket.on('data', (data) => {
   *   console.log('Received:', String.fromCharCode.apply(null, new Uint8Array(data)));
   * });
   *
   * await socket.connect(8080, 'example.com');
   * await socket.write('Hello, World!', {
   *   tags: { message_type: 'greeting' }
   * });
   * ```
   */
  export class Socket {
    /**
     * The current state of the socket connection.
     *
     * Provides detailed information about the socket's lifecycle state,
     * similar to Node.js net.Socket readyState.
     * 
     * Read this property to check the connection status before performing
     * operations or for debugging connection issues.
     *
     * @example
     * ```typescript
     * console.log('Socket state:', socket.ready_state);
     * // Output: 'disconnected', 'opening', 'open', or 'destroyed'
     * 
     * // Check before writing
     * if (socket.ready_state === 'open') {
     *   await socket.write('Hello!');
     * }
     * ```
     */
    ready_state: SocketState;

    /**
     * The local IP address used for this connection.
     * 
     * Available after the socket is connected. Useful for debugging
     * network routing or when testing from hosts with multiple interfaces.
     * 
     * @example
     * ```typescript
     * socket.on('connect', () => {
     *   console.log(`Connected from ${socket.local_ip}:${socket.local_port}`);
     * });
     * ```
     */
    local_ip?: string;

    /**
     * The local port number used for this connection.
     * 
     * Available after the socket is connected. The OS typically assigns
     * an ephemeral port from the available port range.
     */
    local_port?: number;

    /**
     * The remote IP address of the connected server.
     * 
     * Available after DNS resolution completes during connection.
     * This shows the actual IP address even if you connected using a hostname.
     */
    remote_ip?: string;

    /**
     * The remote port number of the connected server.
     * 
     * This is the port you specified in the connection options or connect call.
     */
    remote_port?: number;

    /**
     * Total number of bytes successfully sent through this socket.
     * 
     * Increments with each write() operation. Useful for tracking
     * data transfer volumes in metrics and debugging.
     * 
     * @example
     * ```typescript
     * await socket.write('Hello');
     * console.log(`Sent ${socket.bytes_written} bytes total`);
     * ```
     */
    bytes_written: number;

    /**
     * Total number of bytes received through this socket.
     * 
     * Increments with each 'data' event. Useful for tracking
     * received data volumes and bandwidth usage.
     * 
     * @example
     * ```typescript
     * socket.on('data', (data) => {
     *   console.log(`Received ${data.byteLength} bytes (${socket.bytes_read} total)`);
     * });
     * ```
     */
    bytes_read: number;

    /**
     * Indicates whether the socket is currently connected to a remote endpoint.
     *
     * This is a convenience property that returns `true` when `ready_state` is `'open'`,
     * and `false` otherwise. It provides a simple boolean check for connection status.
     *
     * @example
     * ```typescript
     * if (socket.connected) {
     *   await socket.write('Hello!');
     * } else {
     *   console.log('Socket not connected');
     * }
     * ```
     */
    readonly connected: boolean;

    /**
     * Creates a new TCP socket instance.
     *
     * The socket is created in a disconnected state. Use `connect()` to establish a connection.
     *
     * @param options Optional configuration for the socket
     * @example
     * ```typescript
     * // Create a basic socket
     * const socket = new Socket();
     *
     * // Create a socket with tags for metrics
     * const taggedSocket = new Socket({
     *   tags: { component: 'api-client', version: '1.0' }
     * });
     * ```
     */
    constructor(options?: SocketOptions);

    /**
     * Asynchronously establishes a TCP connection to the specified host and port.
     * 
     * Returns a Promise that resolves when the connection is established,
     * or rejects on connection failure. This is useful for sequential operations
     * where you need to ensure the connection is ready before proceeding.
     * 
     * @param port The destination port number or numeric string (1-65535)
     * @param host The destination hostname or IP address. Defaults to 'localhost'
     * @returns A Promise that resolves when connected successfully
     * @example
     * ```typescript
     * try {
     *   await socket.connect(8080, 'example.com');
     *   console.log('Connected to server');
     *   await socket.write('Hello!');
     * } catch (error) {
     *   console.error('Connection failed:', error);
     * }
     * ```
     */
    connect(port: number | string, host?: string): Promise<void>;

    /**
     * Asynchronously establishes a TCP connection using detailed options.
     * 
     * Returns a Promise that resolves when the connection is established,
     * or rejects on connection failure. Useful for async/await workflows.
     * 
     * @param options Connection options including port, host, TLS, and tags
     * @returns A Promise that resolves when connected successfully
     * @example
     * ```typescript
     * // Connect with TLS
     * await socket.connect({
     *   port: 443,
     *   host: 'secure.example.com',
     *   tls: true,
     *   tags: { protocol: 'https' }
     * });
     * console.log('Secure connection established');
     * ```
     */
    connect(options: ConnectOptions): Promise<void>;

    /**
     * Asynchronously sends data on the socket with additional options.
     * Returns a Promise that resolves when the data has been written to the socket.
     * @param data The data to write - can be a string or ArrayBuffer for binary data
     * @param options Optional configuration options for the write operation
     * @returns A Promise that resolves when the data has been successfully written
     * @example
     * ```typescript
     * // Write with encoding
     * await socket.write('SGVsbG8gV29ybGQ=', { encoding: 'base64' });
     *
     * // Write with tags for metrics
     * await socket.write('Hello, server!', {
     *   tags: { operation: 'handshake', protocol: 'custom' }
     * });
     *
     * // Write with both encoding and tags
     * await socket.write('encoded-payload', {
     *   encoding: 'hex',
     *   tags: { data_type: 'binary', size: 'small' }
     * });
     * ```
     */
    write(data: string | ArrayBuffer, options?: WriteOptions): Promise<void>;

    /**
     * Destroys the socket and closes the connection.
     * 
     * Once destroyed, the socket cannot be reused. All pending operations will
     * be terminated and a 'close' event will be emitted.
     * @example
     * ```typescript
     * // Clean shutdown
     * socket.destroy();
     *
     * // Common pattern: destroy after data received
     * socket.on('data', (data) => {
     *   processData(data);
     *   socket.destroy();
     * });
     * ```
     */
    destroy(): void;

    /**
     * Sets the socket timeout for inactivity.
     *
     * Sets the socket to timeout after `timeout` milliseconds of inactivity on the socket.
     * By default, TCP sockets do not have a timeout. When an idle timeout is triggered,
     * the socket will receive a 'timeout' event but the connection will not be severed.
     * The user must manually call `destroy()` to end the connection.
     *
     * If `timeout` is 0, then the existing idle timeout is disabled.
     *
     * @param timeout Timeout duration in milliseconds. Use 0 to disable timeout
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * // Set a 30-second timeout
     * socket.setTimeout(30000);
     * socket.on('timeout', () => {
     *   console.log('Socket timed out');
     *   socket.destroy();
     * });
     *
     * // Disable timeout
     * socket.setTimeout(0);
     * ```
     */
    setTimeout(timeout: number): this;

    /**
     * Registers an event listener for the 'connect' event.
     *
     * The 'connect' event is emitted when the socket successfully establishes
     * a connection to the remote server. This indicates the socket is ready
     * for reading and writing data.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'connect'
     * @param listener Callback function invoked when the connection is established
     * @example
     * ```typescript
     * socket.on('connect', () => {
     *   console.log('Connected! Ready to send data.');
     *   socket.write('Hello, server!').catch(console.error);
     * });
     * ```
     */
    on(event: 'connect', listener: () => void): void;

    /**
     * Registers an event listener for the 'data' event.
     *
     * The 'data' event is emitted when data is received from the remote endpoint.
     * The data is provided as an Uint8Array for efficient binary data handling.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'data'
     * @param listener Callback function invoked when data is received
     * @example
     * ```typescript
     * socket.on('data', (data) => {
     *   const text = String.fromCharCode.apply(null, data);
     *   console.log('Received:', text);
     *
     *   // Or handle binary data directly
     *   console.log('Binary data:', data);
     * });
     * ```
     */
    on(event: 'data', listener: (data: Uint8Array) => void): void;

    /**
     * Registers an event listener for the 'close' event.
     *
     * The 'close' event is emitted when the socket connection is fully closed
     * by either the local or remote endpoint. This is the final event in the
     * socket lifecycle.
     * 
     * This event is guaranteed to be emitted exactly once per socket, making it
     * ideal for cleanup operations and resolving promises in async patterns.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'close'
     * @param listener Callback function invoked when the socket closes
     * @example
     * ```typescript
     * // Basic usage
     * socket.on('close', () => {
     *   console.log('Connection closed');
     * });
     * 
     * // Async pattern with Promise
     * const closePromise = new Promise((resolve) => {
     *   socket.on('close', resolve);
     * });
     * 
     * await socket.connect(8080, 'example.com');
     * await closePromise; // Wait for connection to close
     * ```
     */
    on(event: 'close', listener: () => void): void;

    /**
     * Registers an event listener for the 'error' event.
     *
     * The 'error' event is emitted when a socket error occurs, such as
     * connection failures, network issues, or protocol errors. It's crucial
     * to handle this event to prevent unhandled errors.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'error'
     * @param listener Callback function invoked when an error occurs, receives the Error object
     * @example
     * ```typescript
     * socket.on('error', (error) => {
     *   console.error('Connection failed:', error.message);
     *   // Handle the error appropriately
     *   socket.destroy();
     * });
     * ```
     */
    on(event: 'error', listener: (error: Error) => void): void;

    /**
     * Registers an event listener for the 'timeout' event.
     *
     * The 'timeout' event is emitted when the socket times out due to inactivity
     * as configured by `setTimeout()`. Note that the socket is not automatically
     * destroyed after a timeout - you must manually call `destroy()` if needed.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'timeout'
     * @param listener Callback function invoked when the socket times out
     * @example
     * ```typescript
     * socket.setTimeout(30000); // Set 30-second timeout
     * socket.on('timeout', () => {
     *   console.log('Connection timed out after 30 seconds');
     *   socket.destroy(); // Manually close the socket
     * });
     * ```
     */
    on(event: 'timeout', listener: () => void): void;
  }
}
