name: Bug report
description: Use this template for reporting bugs. Please search existing issues first.
title: ''
labels: bug
body:
  - type: textarea
    attributes:
      label: Brief summary
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Environment'
  - type: input
    attributes:
      label: k6 version
    validations:
      required: true
  - type: input
    attributes:
      label: OS
      description: e.g. Windows 10, Arch Linux, macOS 11, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Docker version and image (if applicable)
  - type: markdown
    attributes:
      value: '## Detailed issue description'
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
    validations:
      required: true
