name: Feature Request
description: Use this template for suggesting new features.
labels: feature
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the problem or missing capability
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Solution (optional)
      description: If you have a solution in mind, please describe it.
  - type: textarea
    attributes:
      label: Already existing or connected issues / PRs (optional)
      description: If you have found some issues or pull requests that are related to your new issue, please link them here.
