package fs

import "go.k6.io/k6/js/common"

const fsErrorConstructorName = "FSError"

// fsError represents a custom error object emitted by the fs module.
type fsError struct {
	*common.JSError

	// kind contains the kind of error that has occurred.
	kind errorKind
}

// newFsError creates a new Error object of the provided kind and with the
// provided message.
func newFsError(k errorKind, message string) *fsError {
	return &fsError{
		JSError: common.NewJSError(common.JSErrorConfig{
			Constructor: fsErrorConstructorName,
			Name:        k.String(),
			Message:     message,
		}),
		kind: k,
	}
}

// errorKind indicates the kind of file system error that has occurred.
//
// Its string representation is generated by the `enumer` tool. The
// `enumer` tool is run by the `go generate` command. See the `go generate`
// command documentation.
// The tool itself is not tracked as part of the k6 go.mod file, and
// therefore must be installed manually using `go install github.com/dmarkham/enumer`.
//
//go:generate go run github.com/dmarkham/enumer@v1.5.11 -type=errorKind -output errors_gen.go
type errorKind uint8

const (
	// NotFoundError is emitted when a file is not found.
	NotFoundError errorKind = iota + 1

	// InvalidResourceError is emitted when a resource is invalid: for
	// instance when attempting to open a directory, which is not supported.
	InvalidResourceError

	// ForbiddenError is emitted when an operation is forbidden.
	ForbiddenError

	// TypeError is emitted when an incorrect type has been used.
	TypeError

	// EOFError is emitted when the end of a file has been reached.
	EOFError
)

// Ensure that the Error type implements the Go `error` interface.
var (
	_ error              = (*fsError)(nil)
	_ common.JSException = (*fsError)(nil)
)
