name: golangci-lint-k6
description: Run golangci-lint with the k6 ruleset

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
        check-latest: true
    - name: Get golangci-lint version and download rules
      shell: bash
      env: #TODO: remove after https://github.com/actions/runner/issues/2473 is fixed
        GITHUB_ACTION_REF: ${{ github.action_ref || github.head_ref }}
      run: |
        branch="master"
        if [ "${{ github.event.pull_request.head.repo.full_name }}" = "grafana/k6" ]; then
            branch="${{ env.GITHUB_ACTION_REF }}"
        fi
        rules_url="https://raw.githubusercontent.com/grafana/k6/${branch}/.golangci.yml"
        echo "Downloading '${rules_url}' ..."
        curl --silent --show-error --fail --no-location "${rules_url}" --output "${{ github.action_path }}/.golangci.yml"

        echo "GolangCIVersion=$(head -n 1 "${{ github.action_path }}/.golangci.yml" | tr -d '# ')" >> "${GITHUB_OUTPUT}"
      id: getenv
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ steps.getenv.outputs.GolangCIVersion }}
        only-new-issues: true
        args: "--config=${{ github.action_path }}/.golangci.yml"
