name: golangci-lint-k6
description: Run golangci-lint with the k6 ruleset

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
        check-latest: true
    - name: Get golangci-lint version and download rules
      shell: bash
      env:
        GITHUB_ACTION_REF: ${{ github.action_ref }}
        GITHUB_HEAD_REF: ${{  github.head_ref }}
        REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
      run: |
        branch="master"
        if [ "${REPO_FULL_NAME}" = "grafana/k6" ]; then
          branch="${GITHUB_ACTION_REF:-${GITHUB_HEAD_REF}}"
        fi
        rules_url="https://raw.githubusercontent.com/grafana/k6/${branch}/.golangci.yml"
        echo "Downloading '${rules_url}' ..."
        curl --silent --show-error --fail --no-location "${rules_url}" --output "${{ github.action_path }}/.golangci.yml"

        echo "GolangCIVersion=$(head -n 1 "${{ github.action_path }}/.golangci.yml" | tr -d '# ')" >> "${GITHUB_OUTPUT}"
      id: getenv
    - name: golangci-lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: ${{ steps.getenv.outputs.GolangCIVersion }}
        args: "--config=${{ github.action_path }}/.golangci.yml"
