name: golangci-lint-k6
description: Run golangci-lint with the k6 ruleset

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version: 1.26.x
        check-latest: true
    - name: Get golangci-lint version and download rules
      shell: bash
      env:
        GITHUB_ACTION_REF: ${{ github.action_ref }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
      run: |
        branch="${GITHUB_HEAD_REF:-master}"
        if [ "${REPO_FULL_NAME}" != "grafana/k6" ]; then
          branch="${GITHUB_ACTION_REF:-master}"
        fi
        rules_url="https://raw.githubusercontent.com/grafana/k6/${branch}/.golangci.yml"
        echo "Downloading '${rules_url}' ..."
        curl --silent --show-error --fail --no-location "${rules_url}" --output "${{ github.action_path }}/.golangci.yml"

        echo "GolangCIVersion=$(head -n 1 "${{ github.action_path }}/.golangci.yml" | tr -d '# ')" >> "${GITHUB_OUTPUT}"
      id: getenv
    - name: golangci-lint
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        version: ${{ steps.getenv.outputs.GolangCIVersion }}
        args: "--config=${{ github.action_path }}/.golangci.yml"
