name: golangci-lint-k6
description: Run golangci-lint with the k6 ruleset

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
        check-latest: true
    - name: Get golangci-lint version and download rules
      shell: bash
      env: #TODO: remove after https://github.com/actions/runner/issues/2473 is fixed
        GITHUB_ACTION_REF: ${{ github.action_ref || github.head_ref }}
      run: |
        branch="master"
        if [ "${{ github.event.pull_request.head.repo.full_name }}" = "grafana/k6" ]; then
            branch="${{ env.GITHUB_ACTION_REF }}"
        fi
        rules_url="https://raw.githubusercontent.com/grafana/k6/${branch}/.golangci.yml"
        echo "Downloading '${rules_url}' ..."
        curl --silent --show-error --fail --no-location "${rules_url}" --output "${{ github.action_path }}/.golangci.yml"

        echo "GolangCIVersion=$(head -n 1 "${{ github.action_path }}/.golangci.yml" | tr -d '# ')" >> "${GITHUB_OUTPUT}"
      id: getenv
    - name: golangci-lint
      # Here, we play safe and use directly the hash of the version,
      # instead of using a versioning tag that might be overwritten in the future.
      # The hash below links to v6.2.0
      uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae
      with:
        version: ${{ steps.getenv.outputs.GolangCIVersion }}
        args: "--config=${{ github.action_path }}/.golangci.yml"
