version: '3'
services:
  build-linux-packages:
    build:
      context: .
      dockerfile: Dockerfile.linux
    command: |
      bash -c "
      CGO_ENABLED=0 GOARCH=amd64 go build -a -ldflags '-s -w' -o /tmp/k6
      /go/src/github.com/loadimpact/k6/packaging/gen-packages.sh"
    volumes:
      - ..:/go/src/github.com/loadimpact/k6