services:
  packager:
    build:
      context: .
    image: ghcr.io/grafana/k6packager:latest
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_CF_DISTRIBUTION
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - PGP_SIGN_KEY_PASSPHRASE
      - S3_BUCKET
    volumes:
      - ../dist:/home/k6/dist
      - ./sign-key.gpg:/home/k6/sign-key.gpg
