name: Auto-approve Renovate
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
  checks: read
  statuses: read
  id-token: write
jobs:
  approve:
    uses: grafana/k6-ci/.github/workflows/auto-approve-renovate.yml@41aaf8e365b56fd120b0396beae2eba3969babab # v0.5.1
