name: E2E
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'release notes/**'
  schedule:
    # At 06:00 AM UTC from Monday through Friday
    - cron:  '0 6 * * 1-5'

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
#        go: [stable, tip]
        go: [stable]
        platform: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
#        platform: [ubuntu-latest]
        include:
          - platform: ubuntu-latest
            docker: true
          - platform: ubuntu-24.04-arm
            docker: true
          - platform: windows-latest
            docker: false
          - platform: macos-latest
            docker: false
    runs-on: ${{ matrix.platform }}
    env:
      TEST_OUTPUT_DIR: ${{ github.workspace }}/e2e-output
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: 1.x
          check-latest: true
          cache: false # against cache-poisoning
      - name: Install Go tip
        if: matrix.go == 'tip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ matrix.platform }} --repo grafana/gotip --pattern 'go.zip'
          unzip go.zip -d $HOME/sdk
          echo "GOROOT=$HOME/sdk/gotip" >> "$GITHUB_ENV"
          echo "GOPATH=$HOME/go" >> "$GITHUB_ENV"
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
          echo "$HOME/sdk/gotip/bin" >> "$GITHUB_PATH"
      - name: Build k6
        run: |
          which go
          go version

          go build .
          ./k6 version
      - name: Prepare Output Directory
        run: |
          mkdir -p "${{ env.TEST_OUTPUT_DIR }}"
          chmod 777 "${{ env.TEST_OUTPUT_DIR }}"
      - name: Run E2E tests - On host
        if: matrix.docker == false
        run: |
          set -x
          export K6_BROWSER_HEADLESS=true
          export K6_NO_USAGE_REPORT=true
          export E2E_OUTPUT_PATH="${{ env.TEST_OUTPUT_DIR }}"

          for f in examples/browser/*.js; do
            if [ "$f" == "examples/browser/hosts.js" ] && [ "$RUNNER_OS" == "Windows" ]; then
              echo "skipping $f on Windows"
              continue
            fi
            ./k6 run -q "$f"
          done

      - name: Build docker image
        if: matrix.docker == true
        run: docker buildx build --target with-browser --load -t k6-browser:test .
      - name: Run E2E tests - In Docker
        if: matrix.docker == true
        run: |
          set -x

          cd examples/browser
          for f in *.js; do
            # E2E_OUTPUT_PATH controls where the screenshot test stores the screenshot.
            # By default it writes into the home directory, which we can't mount to without breaking Chrome.
            docker run --rm \
              --pull never \
              --env K6_NO_USAGE_REPORT=true \
              --env E2E_OUTPUT_PATH=/output \
              -v "$PWD:/tests" \
              -v "${{ env.TEST_OUTPUT_DIR }}:/output" \
            k6-browser:test run -q "/tests/$f"
          done
      - name: Check screenshot
        # TODO: Do something more sophisticated?
        run: test -s "${{ env.TEST_OUTPUT_DIR }}/screenshot.png"
