name: Build
on:
  workflow_dispatch:
    inputs:
      k6_version:
        description: 'The version of the release, it must use the semantic versioning format with the v prefix. It is a development release so it is suggested to append a build metadata (e.g. v0.38.0-dev).'
        required: true
      go_version:
        description: 'Go version for building binaries'
        default: '1.x'
        required: true
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read

env:
  APP_NAME: "k6"
  DOCKER_IMAGE_ID: "grafana/k6"
  GHCR_IMAGE_ID: ${{ github.repository }}
  DEFAULT_GO_VERSION: "1.24.x"

jobs:
  build:
    runs-on: ubuntu-latest
    # needs: [configure, build, package-windows]
    # if: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name != 'workflow_dispatch' }}
    # env:
    #   VERSION: ${{ needs.configure.outputs.k6_version }}
    permissions:
      actions: read
      contents: read
      packages: read
      id-token: write # required for AWS authentication
    steps:
      # - uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets-v1.2.0
      #   with:
      #     # arn:.../k6-uploader-role
      #     repo_secrets: |
      #       IAM_ROLE_ARN=deploy:uploader-iam-role 

      - name: aws-auth
        uses: grafana/shared-workflows/actions/aws-auth@aws-auth-v1.0.1
        with:
          aws-region: 'us-east-2'
          # role-arn: '${{ env.IAM_ROLE_ARN }}'
          set-creds-in-environment: true

      # - name: Get Codecov token
      #   uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets/v1.2.1
      #   with:
      #     repo_secrets: |
      #       AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:AWS_ACCESS_KEY_ID
      #       AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:AWS_SECRET_ACCESS_KEY
      #       AWS_CF_DISTRIBUTION=AWS_CF_DISTRIBUTION:AWS_CF_DISTRIBUTION
      - name: Setup docker compose environment
        run: |
          cat > packaging/.env <<EOF
          AWS_DEFAULT_REGION=us-east-2
          AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_CF_DISTRIBUTION="${{ env.AWS_CF_DISTRIBUTION }}"
          PGP_SIGN_KEY_PASSPHRASE=${{ secrets.PGP_SIGN_KEY_PASSPHRASE }}
          EOF
          echo "${{ secrets.PGP_SIGN_KEY }}" > packaging/sign-key.gpg
      # - name: Publish packages
      #   env:
      #     GITHUB_ACTOR: ${{ github.actor }}
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      #     cd packaging
      #     docker compose pull packager
      #     docker compose run --rm packager
