name: syft-sbom-ci

on:
  release:
    types: [created]

jobs:
  syft-sbom:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Anchore SBOM Action
      uses: anchore/sbom-action@v0.12.0
      with:
         artifact-name: ${{ github.event.repository.name }}-spdx.json

